version: "3.9"

services:
  api:
    container_name: api
    image: backend:latest
    restart: always
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./api/.env

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
